name: conv_onet
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - cython=0.29.34
  - imageio=2.28.1
  - numpy=1.24.3
  - numpy-base=1.24.3
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - pandas=2.0.1
  - pillow=9.4.0
  - pytest=7.3.1
  - python=3.8.16
  - pyyaml=6.0
  - scikit-image=0.20.0
  - scipy=1.9.0
  - tqdm=4.65.0
  - trimesh=3.21.6
  - pip:
    - tensorboardx==2.6
    - pyembree==0.2.11
    - h5py==3.8.0
    - plyfile==0.9